name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd "fastcgi helloworld" && docker build . --file Dockerfile --tag fastcgi:$(date +%s)
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image 2
        run: cd "fastcgi with file loader" && docker build . --file Dockerfile --tag fastcgi2:$(date +%s)
